### ISSUE TITLE
Getting ENOENT when ctrl+c'ing my server

### ISSUE THREAD

**Issue by AdriVanHoudt** [nearform/node-clinic-doctor#93] opened 2018-01-25 09:09 UTC
```
/Users/adri/.npm/_npx/35397/lib/node_modules/clinic/bin.js:192
      if (err) throw err
               ^

Error: ENOENT: no such file or directory, rename 'node_trace.1.log' -> '35409.clinic-doctor/35409.clinic-doctor-traceevent'
```

I am getting a `35409.clinic-doctor` folder with a `processstat` and `systeminfo` file
```js
$ cat 35409.clinic-doctor/35409.clinic-doctor-systeminfo
{
  "clock": {
    "hrtime": [
      368808,
      367953458
    ],
    "unixtime": 1516870162500
  },
  "nodeVersions": {
    "http_parser": "2.7.0",
    "node": "8.9.4",
    "v8": "6.1.534.50",
    "uv": "1.15.0",
    "zlib": "1.2.11",
    "ares": "1.10.1-DEV",
    "modules": "57",
    "nghttp2": "1.25.0",
    "openssl": "1.0.2n",
    "icu": "59.1",
    "unicode": "9.0",
    "cldr": "31.0.1",
    "tz": "2017b"
  },
  "toolVersion": "0.6.0"
}
```

**Comment by AndreasMadsen** [comment] 2018-01-25 10:06
@AdriVanHoudt Thanks for the report. Could you try node 9.4.0?

This is properly caused by a bug in node.js that we recently fixed (https://github.com/nodejs/node/pull/18005). The bugfix is in node 9.4.0 and will be in node 8.10.0. Unfortunately, node 8.9.4 doesn't have the bugfix.

**Comment by AdriVanHoudt** [comment] 2018-01-25 10:47
Ok that worked, fancy graphs ✨ 👌
Can I recommend putting that in the readme or something? I read somewhere that older version of 8 and 9 might not work but this means the latests of 8 even doesn't work.

Also where do I go to fix a link in the reference of a recommandation?

**Comment by AdriVanHoudt** [comment] 2018-01-25 10:48
(you can close this as you deem necessary)

**Comment by AndreasMadsen** [comment] 2018-01-25 10:51
@AdriVanHoudt Yep. We will be adding some engine fields. The release of node v8.10.0 is going to happen much later than we had hoped.

> Also where do I go to fix a link in the reference of a recommandation?

That is pretty easy, you can find the markdown files here:
https://github.com/nearform/node-clinic-doctor/tree/master/recommendations

**Comment by AdriVanHoudt** [comment] 2018-01-25 12:35
done https://github.com/nearform/node-clinic-doctor/pull/95 📝

**Comment by AndreasMadsen** [comment] 2018-01-30 11:37
The documentation have been updated. This is thus "fixed" :)

**Closed by AndreasMadsen** 2018-01-30 11:37 UTC
